# Generated by Django 4.2.5 on 2023-10-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'login_info',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('yourname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
